#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

[ -f ~/.xprofile ] && source ~/.xprofile
# Randomly change wallpaper
feh --bg-max --randomize ~/.wallpaper/* &
/usr/bin/VBoxClient-all
# Run i3
exec i3
 
